/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Color;
import swing.TextBubbleBorder;

/**
 *
 * @author Admin
 */
public class ChatLeft extends javax.swing.JPanel {

    /**
     * Creates new form ChatLeft
     * @param text
     */
    public ChatLeft(String text) {
        initComponents();
        textPane.setText(text);
        textPane.setBorder(new TextBubbleBorder(Color.WHITE,2,16,16));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textPane = new javax.swing.JTextPane();

        setBackground(new java.awt.Color(255, 255, 255));

        textPane.setEditable(false);
        textPane.setBackground(new java.awt.Color(228, 230, 235));
        textPane.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        textPane.setMargin(new java.awt.Insets(6, 3, 3, 3));
        add(textPane);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane textPane;
    // End of variables declaration//GEN-END:variables
}
