/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import javax.swing.JScrollBar;
import javax.swing.SwingUtilities;
import net.miginfocom.swing.MigLayout;
import swing.ScrollBar;

/**
 *
 * @author Admin
 */
public class ChatPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChatPanel
     */

    public ChatPanel() {      
        initComponents();
        jPanel_background.setLayout(new MigLayout("fillx", "", "10[]10"));
        jScrollPane1.setVerticalScrollBar(new ScrollBar());
    }
 
    public void addChatLeft(String text) {
        ChatLeft chatleft = new ChatLeft(text);
        jPanel_background.add(chatleft, "wrap, w ::90%");
        jPanel_background.repaint();
        jPanel_background.revalidate();
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {        
                JScrollBar vertical = jScrollPane1.getVerticalScrollBar();
                vertical.setValue(vertical.getMaximum());            
            }            
        });
    }
    public void addChatRight(String text) {
        ChatRight chatright = new ChatRight(text);
        jPanel_background.add(chatright, "wrap, al right, w ::90%");
        jPanel_background.repaint();
        jPanel_background.revalidate();       
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {        
                JScrollBar vertical = jScrollPane1.getVerticalScrollBar();
                vertical.setValue(vertical.getMaximum());            
            }            
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel_background = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(790, 480));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel_background.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel_backgroundLayout = new javax.swing.GroupLayout(jPanel_background);
        jPanel_background.setLayout(jPanel_backgroundLayout);
        jPanel_backgroundLayout.setHorizontalGroup(
            jPanel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 769, Short.MAX_VALUE)
        );
        jPanel_backgroundLayout.setVerticalGroup(
            jPanel_backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel_background);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel_background;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
