package form;


import control.Client;
import java.awt.Color;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.io.IOException;
import java.net.Socket;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import swing.TextBubbleBorder;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class ConnectView extends javax.swing.JFrame {

    private static ConnectView conview;
    boolean isConnect;
    Client client;

    private Connection con;
    String logchat;
    private Socket socket;
    
    private int lastX;
    private int lastY;
    /**
     * Creates new form ConnectView
     */
    public ConnectView() {
        initComponents();
        setLocationRelativeTo(null);
        jTextField_iproom.setBorder(new TextBubbleBorder(Color.WHITE,2,13,5));
        jTextField_username.setBorder(new TextBubbleBorder(Color.WHITE,2,13,5));
        jPasswordField1.setBorder(new TextBubbleBorder(Color.WHITE,2,13,5));
        jPanel3.setBorder(new TextBubbleBorder(Color.WHITE,0,1,16));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_iproom = new javax.swing.JTextField();
        jTextField_username = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_username100 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(242, 242, 242));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(46, 46, 46));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Connect");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 430, 200, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-server-60.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/padlock.png"))); // NOI18N
        jLabel6.setAlignmentY(0.0F);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jTextField_iproom.setBackground(new java.awt.Color(237, 242, 245));
        jTextField_iproom.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField_iproom.setText("127.0.0.1");
        jTextField_iproom.setAutoscrolls(false);
        jTextField_iproom.setMargin(new java.awt.Insets(2, 10, 2, 2));
        jTextField_iproom.setCaretPosition(9);
        jTextField_iproom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_iproomMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField_iproomMousePressed(evt);
            }
        });
        jTextField_iproom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_iproomKeyPressed(evt);
            }
        });
        jPanel2.add(jTextField_iproom, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 357, 56));

        jTextField_username.setBackground(new java.awt.Color(237, 242, 245));
        jTextField_username.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField_username.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_username.setText("Enter your name");
        jTextField_username.setAutoscrolls(false);
        jTextField_username.setMargin(new java.awt.Insets(2, 16, 2, 2));
        jTextField_username.setPreferredSize(new java.awt.Dimension(89, 28));
        jTextField_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_usernameMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField_usernameMousePressed(evt);
            }
        });
        jTextField_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_usernameKeyPressed(evt);
            }
        });
        jPanel2.add(jTextField_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 357, 53));

        jPasswordField1.setBackground(new java.awt.Color(237, 242, 245));
        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setMargin(new java.awt.Insets(2, 16, 2, 2));
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPanel2.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 350, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Icon-Notification@3x.png"))); // NOI18N
        jLabel9.setAlignmentY(0.0F);
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jTextField_username100.setBackground(new java.awt.Color(237, 242, 245));
        jTextField_username100.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextField_username100.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_username100.setText("Enter your name");
        jTextField_username100.setAutoscrolls(false);
        jTextField_username100.setMargin(new java.awt.Insets(2, 16, 2, 2));
        jTextField_username100.setPreferredSize(new java.awt.Dimension(89, 28));
        jTextField_username100.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField_username100MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField_username100MousePressed(evt);
            }
        });
        jTextField_username100.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_username100KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField_username100, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 357, 53));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 70, -1, 380));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Chat Application");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, -1, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel7MouseDragged(evt);
            }
        });
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel7MousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_circled_x_24px.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(1094, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/undraw_remotely_2j6y.png"))); // NOI18N
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Bạn chưa có tài khoản ?");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 570, -1, -1));

        jLabel7.setBackground(new java.awt.Color(51, 102, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("Đăng ký ngay");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 570, -1, -1));
        Font font = jLabel7.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        jLabel7.setFont(font.deriveFont(attributes));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        if(!jTextField_username.getText().equals("Enter your name") && !jTextField_username.getText().equals("") && !jTextField_iproom.getText().equals("")) { // Ngan chan 1 client connect 2 lan                     
            try {
                    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                    String dbUrl = "jdbc:sqlserver://ADMIN-PC:1433;databaseName=MessLibrary;user=sa;password=sa2008";
                    con = DriverManager.getConnection(dbUrl);
                    JOptionPane.showMessageDialog(conview, "Connected SQL success!", "Dialog",JOptionPane.INFORMATION_MESSAGE);
                    isConnect = true;
                } catch (ClassNotFoundException | SQLException e) {
                    isConnect = false;
            }
            try {
                String sqlSelect = "SELECT * FROM UserInfo WHERE UserName = ? AND Password = ?";
                PreparedStatement stmt = con.prepareStatement(sqlSelect);
                stmt.setNString(1, jTextField_username.getText());
                stmt.setNString(2, jPasswordField1.getText());

                ResultSet rs = stmt.executeQuery();
                if (rs.next()) {
                    if (isConnect) { // Kiem ket noi SQL
                        ClientView clientview;
                        try {
                            socket = new Socket(jTextField_iproom.getText(), 1234); // Yeu cau ket noi toi SERVER
                            String username = jTextField_username.getText();
                            client = new Client(socket, username); // Khoi client voi 1 socket va Username

                            // Open ClientView
                            clientview = new ClientView(con, client, conview);
                            clientview.setVisible(true);

                            conview.setVisible(false);
                            conview.setDefaultCloseOperation(conview.EXIT_ON_CLOSE);
                            conview.dispose();
                            client.listenForMessage(clientview);
                        } catch (IOException e) {
                            JOptionPane.showMessageDialog(conview, "Can't Connected Server!", "Dialog", JOptionPane.ERROR_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(conview, "Can't Connected SQL!", "Dialog", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Sai tài khoản hoặc mật khẩu", "Thông Báo", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
        else JOptionPane.showMessageDialog(conview, "Vui Long Nhap Du Thong Tin!", "Dialog",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        if(jTextField_username.getText().equals("")) {
            jTextField_username.setForeground(new java.awt.Color(153, 153, 153));
            jTextField_username.setText("Enter your name");
        }
        if(jTextField_iproom.getText().equals(""))
            jTextField_iproom.setText("127.0.0.1");
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jTextField_iproomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_iproomMouseClicked
        if(jTextField_username.getText().equals("")) {
            jTextField_username.setForeground(new java.awt.Color(153, 153, 153));
            jTextField_username.setText("Enter your name");
        }
        if(jTextField_iproom.getText().equals(""))
            jTextField_iproom.setText("127.0.0.1");
    }//GEN-LAST:event_jTextField_iproomMouseClicked

    private void jTextField_iproomKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_iproomKeyPressed
        if (evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
            if(!jTextField_username.getText().equals("Enter your name") && !jTextField_username.getText().equals("") && !jTextField_iproom.getText().equals("")) { // Ngan chan 1 client connect 2 lan                     
                try {
                        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                        String dbUrl = "jdbc:sqlserver://ADMIN-PC:1433;databaseName=MessLibrary;user=sa;password=sa2008";
                        con = DriverManager.getConnection(dbUrl);
                        JOptionPane.showMessageDialog(conview, "Connected SQL success!", "Dialog",JOptionPane.INFORMATION_MESSAGE);
                        isConnect = true;
                    } catch (ClassNotFoundException | SQLException e) {
                        isConnect = false;
                    }
                if(isConnect) { // Kiem ket noi SQL
                    ClientView clientview;
                    try {
                        socket = new Socket(jTextField_iproom.getText(), 1234); // Yeu cau ket noi toi SERVER
                        String username = jTextField_username.getText();
                        client = new Client(socket, username); // Khoi client voi 1 socket va Username

                        // Open ClientView
                        clientview = new ClientView(con, client, conview);
                        clientview.setVisible(true);

                        conview.setVisible(false);
                        conview.setDefaultCloseOperation(conview.EXIT_ON_CLOSE);
                        conview.dispose();
                        client.listenForMessage(clientview);
                    } catch (IOException e) {
                        JOptionPane.showMessageDialog(conview, "Can't Connected Server!", "Dialog",JOptionPane.ERROR_MESSAGE);
                    }
                }
                else {
                    JOptionPane.showMessageDialog(conview, "Can't Connected SQL!", "Dialog",JOptionPane.ERROR_MESSAGE);
                }
            }
            else JOptionPane.showMessageDialog(conview, "Vui Long Nhap Du Thong Tin!", "Dialog",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jTextField_iproomKeyPressed

    private void jTextField_iproomMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_iproomMousePressed
        if(jTextField_username.getText().equals("")) {
            jTextField_username.setForeground(new java.awt.Color(153, 153, 153));
            jTextField_username.setText("Enter your name");
        }
        if(jTextField_iproom.getText().equals(""))
            jTextField_iproom.setText("127.0.0.1");
    }//GEN-LAST:event_jTextField_iproomMousePressed

    private void jPanel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MousePressed
        lastX = evt.getXOnScreen();
        lastY = evt.getYOnScreen();
    }//GEN-LAST:event_jPanel7MousePressed

    private void jPanel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        // Move frame by the mouse delta
        setLocation(getLocationOnScreen().x + x - lastX,
            getLocationOnScreen().y + y - lastY);
        lastX = x;
        lastY = y;
    }//GEN-LAST:event_jPanel7MouseDragged

    private void jTextField_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_usernameMouseClicked
        if (jTextField_username.getText().equals("Enter your name")) {
            jTextField_username.setText("");
        }
        jTextField_username.setForeground(new java.awt.Color(0, 0, 0));
        if (jTextField_iproom.getText().equals("")) {
            jTextField_iproom.setText("127.0.0.1");
        }
    }//GEN-LAST:event_jTextField_usernameMouseClicked

    private void jTextField_usernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_usernameMousePressed
        if (jTextField_username.getText().equals("Enter your name")) {
            jTextField_username.setText("");
        }
        jTextField_username.setForeground(new java.awt.Color(0, 0, 0));
        if (jTextField_iproom.getText().equals("")) {
            jTextField_iproom.setText("127.0.0.1");
        }
    }//GEN-LAST:event_jTextField_usernameMousePressed

    private void jTextField_usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_usernameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_usernameKeyPressed

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
      jPasswordField1.setText("");
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        this.dispose();
        Register rg = new Register();
        rg.setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jTextField_username100MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_username100MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_username100MouseClicked

    private void jTextField_username100MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField_username100MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_username100MousePressed

    private void jTextField_username100KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_username100KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_username100KeyPressed
    public void closeSocket() {
        try {
            socket.close();
        } catch (IOException ex) {
            Logger.getLogger(ConnectView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
           UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        conview = new ConnectView();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               conview.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField_iproom;
    private javax.swing.JTextField jTextField_username;
    private javax.swing.JTextField jTextField_username100;
    // End of variables declaration//GEN-END:variables
}
